# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf79e9c1a540a9cc5104c16d08e1f8ce03dead001df68d2bf4a4b554fc0d1e5bb83cd5fd195af4f9ea22ee3ef3f603e00e35544fe54ca1f77f983bda4bbb8a4e

test:
  secret_key_base: 4f61d60a7034b2501ef275ee2da0fa1d02b5060cd479a0bebf72836ae5dd27fd836f243a57eeeaf8f41bc1c01c89756a159501c9935d906f62ecf24bd47296fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
